### ISSUE TITLE
Code plus sain

### ISSUE THREAD

**Issue by Nephos** [Hellfire01/encode-o-matic#1]
- il faut pas push les binaires
- ne plus utiliser les fonctions chelous genre strlen
- faire des classes et aucune fonctions dans le mainscop (sauf les templates)

**Comment by Hellfire01** [comment]
merci de m'avoir signalé le binaire dans le commit.
La prochaine étape sur le code ( dans les deux semaines qui vont suivre ) sera une très grosse factorisation ( en gros : masse de classes, templates, code plus générique, plus de char, ... ).
Le but étant d'obtenir une code plus c++ pour plus de lisibilité ( il est actuellement correct mais sans plus )

**Comment by Nephos** [comment]
Non il est pas correct c'est du C mec :)

**Comment by Hellfire01** [comment]
vais en faire du C++ c'est promis XD ( les méthodes de chiffrement vont être encapsulées dans des classes )
